### ISSUE TITLE
Cannot download files

### ISSUE THREAD

**Issue by miquelduranfrigola** [josejimenezluna/delfta#85]
Hi! Thanks for a great repository.
I am trying to download the files as suggested in the README, but unfortunately I get this error:

```
(delfta) mduranfrigola@raluy:~/Desktop$ python -c "import runpy; _ = runpy.run_module('delfta.download', run_name='__main__')"
2024/04/24 05:17:59 PM | DelFTa | INFO: Now downloading trained models and utils...
Traceback (most recent call last):                                                                                                  
  File "<string>", line 1, in <module>
  File "/home/mduranfrigola/miniconda3/envs/delfta/lib/python3.9/runpy.py", line 228, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/home/mduranfrigola/miniconda3/envs/delfta/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/mduranfrigola/miniconda3/envs/delfta/lib/python3.9/site-packages/delfta/download.py", line 134, in <module>
    _download_required()
  File "/home/mduranfrigola/miniconda3/envs/delfta/lib/python3.9/site-packages/delfta/download.py", line 93, in _download_required
    with tarfile.open(models_tar) as handle:
  File "/home/mduranfrigola/miniconda3/envs/delfta/lib/python3.9/tarfile.py", line 1797, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully
```

Do you know what might be going on?
Thanks a lot in advance.

**Comment by josejimenezluna** [comment]
Hi @miquelduranfrigola, it appears the remotes containing the necessary downloadables are undergoing some issues:

```bash
(base) [hawk31@office ~]$ wget "https://www.research-collection.ethz.ch/bitstream/handle/20.500.11850/520281/utils.tar.gz?sequence=8&isAllowed=y"
--2024-04-24 17:05:07--  https://www.research-collection.ethz.ch/bitstream/handle/20.500.11850/520281/utils.tar.gz?sequence=8&isAllowed=y
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving www.research-collection.ethz.ch (www.research-collection.ethz.ch)... 129.132.8.151
Connecting to www.research-collection.ethz.ch (www.research-collection.ethz.ch)|129.132.8.151|:443... connected.
HTTP request sent, awaiting response... 429 Too Many Requests
2024-04-24 17:05:08 ERROR 429: Too Many Requests.
```

Can I suggest trying again later?

**Comment by miquelduranfrigola** [comment]
Yes of course! There is no rush. Thanks for the prompt reply.

**Comment by cisert** [comment]
Seems to be working now - please recheck again :)

**Comment by miquelduranfrigola** [comment]
It works perfectly now. Thank you so much!
